# Use Node Alpine for lightweight image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install dependencies first to leverage Docker cache
COPY package*.json ./
RUN npm install

# Copy all project files
COPY . .

# Expose Vite dev server port
EXPOSE 5173

# Start dev server using npx to ensure local vite is found
CMD ["npm", "run", "dev--","--host", "0.0.0.0"]
